select cast(PARTNER_ID as int) as PARTNER_ID
      ,cast(ORDER_ID as int) as ORDER_ID
      ,cast(ORDER_ITEM_ID as int) as ORDER_ITEM_ID
      ,cast(VENDOR_ID as int) as VENDOR_ID
      ,VENDOR_NAME
      ,cast(DATE_CREATED as datetime) as DATE_CREATED
      ,cast(IN_PRODUCTION_DATE as datetime) as IN_PRODUCTION_DATE
      ,cast(SHIP_DATE as datetime) as SHIP_DATE
      ,cast(DELIVERED_DATE as datetime) as DELIVERED_DATE
      ,SHIPPING_ADDRESS_LINE1
      ,CITY
      ,STATE
      ,ZIP
      ,COUNTRY
      ,PRODUCT
      ,cast(PRODUCT_ID as int) as PRODUCT_ID
      ,cast(CATEGORY_ID as int) as CATEGORY_ID
      ,PRODUCT_CATEGORY
      ,SKU
      ,cast(SKU_ID as int) as SKU_ID
      ,cast(QUANTITY as int) as QUANTITY
      ,ORDER_STATUS
      ,GOOTEN_SHIPPING_METHOD
      ,CARRIER
      ,PLANNED_CARRIER_METHOD
      ,REFUND_REPRINT_REASON
      ,REPRINT_VS_REFUND
      ,DISCOUNT_AMOUNT
      ,PARTNER_ITEM_COST
      ,CUSTOMER_ITEM_COST
      ,PARTNER_SHIPPING_COST
      ,CUSTOMER_SHIPPING_COST
      ,PARTNER_TOTAL_ITEM_COST
      ,SHIPPING_REFUND_AMOUNT
      ,ITEM_REFUND_AMOUNT
      ,CUSTOMER_TOTAL_ITEM_COST
      ,GOOTEN_ITEM_COST
      ,GOOTEN_SHIPPING_COST
      ,PARTNER_ITEM_PROFIT
      ,PARTNER_CHARGED_AMOUNT
      ,GOOTEN_ORDER_VALUE
      ,GOOTEN_ORDER_VALUE_NET
      ,REVENUE
      ,GOOTEN_TOTAL_COST
      ,GOOTEN_REBATE
      ,NET_REVENUE
      ,PARTNER_TOTAL_TAX
      ,PARTNER_SHIPPING_SURCHARGE
      ,WAS_PRODUCED
      ,IS_IN_PRODUCTION
      ,SUBMISSION_TYPE
      ,PENDING_TIME_DURATION
      ,PRODUCTION_BACKLOG_DAYS
      ,PRODUCTION_DAYS
      ,TRANSIT_DAYS
      ,TRANSIT_BACKLOG_DAYS
      ,ORDER_STAGE
      ,WORKING_DAY_COUNTER_SHIP_DATE
      ,WORKING_DAY_COUNTER_DELIVERY_DATE
      ,WORKING_DAY_COUNTER_IN_PROD_DATE
      ,WORKING_DAY_COUNTER_TODAY
      ,SLA
      ,SLA_MAX
      ,MIN_REFUND_DATE
      ,MIN_REFUND_DATE_EST
      ,SLA_CLEAN
      ,BACKLOG_VAR_TO_SLA
      ,PARTNER_PROGRAM_STATUS
FROM GOOTEN_ANALYTICS_DB.GSHEETS_ORDERS.JAN2021ORDERDATA