
version: 2

models:
    - name: orders
      description: :"Cleaned order data"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null