
version: 2

models:
    - name: orders
      description: :"Cleaned order data"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests:
                - not_null
      tests:
        - unique:
            column_name: "(order_item_id || '-' || order_id)"